---
title: The Wright Life
baseURL: "/"
params:
  palette: blue
  header:
    title: The Wright Life
    tagline: We are glad you are here!
    logo_img: ''
    bg_img: "/images/header-bg.jpg"
    has_nav: true
    has_social: true
  footer:
    content: "&copy; All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
disableKinds:
- RSS
